apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
    isDefault: true
    jsonData:
      sslmode: "disable"
