name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        working-directory: app

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: app

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run ETL unit tests
        run: pytest -v

      - name: Build Docker images
        run: docker compose build
